<#import "parts/common.ftlh" as c>
<@c.page>
    <div class="text-info">
        <div class="mx-auto">
            <h5 style="font-size: 40px">Hello!</h5>
            <div>Welcome to our analog of twitter.</div>
        </div>
        <div class="text-uppercase" style="font-size: 100px; font-weight: bold;">
            <div>
                Tell the<br>
                world about<br>
                your thoughts<br>
            </div>
        </div>
    </div>

</@c.page>